package entity;

import java.sql.Date;

/**
 * Created by Momken on 17.12.2015.
 */
public class Fahrt {
    /*

ID INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1)PRIMARY KEY,
schiffId INTEGER,
hafenVonId INTEGER,
hafenBisId INTEGER,
ladung VARCHAR(60),
abfahrt DATE,
ankunft DATE
     */
    private Integer id = null;
    private Integer schiffID = null;
    private Integer havenVonID = null;
    private Integer hafenBisID = null;
    private String ladung = null;
    private Date abfahrt = null;
    private Date ankunft = null;


    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getSchiffID() {
        return schiffID;
    }

    public void setSchiffID(Integer schiffID) {
        this.schiffID = schiffID;
    }

    public Integer getHavenVonID() {
        return havenVonID;
    }

    public void setHavenVonID(Integer havenVonID) {
        this.havenVonID = havenVonID;
    }

    public Integer getHafenBisID() {
        return hafenBisID;
    }

    public void setHafenBisID(Integer hafenBisID) {
        this.hafenBisID = hafenBisID;
    }

    public String getLadung() {
        return ladung;
    }

    public void setLadung(String ladung) {
        this.ladung = ladung;
    }

    public Date getAbfahrt() {
        return abfahrt;
    }

    public void setAbfahrt(Date abfahrt) {
        this.abfahrt = abfahrt;
    }

    public Date getAnkunft() {
        return ankunft;
    }

    public void setAnkunft(Date ankunft) {
        this.ankunft = ankunft;
    }
}
